wandb_version: 1

_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723108161
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 37
      - 38
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
batch_size:
  desc: null
  value: 128
dropout_rate:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 300
learning_rate:
  desc: null
  value: 0.01
num_layers:
  desc: null
  value: 3
units_layer_1:
  desc: null
  value: 256
units_layer_2:
  desc: null
  value: 256
