wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723298661
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 150
batch_size:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 2
dropout_rate:
  desc: null
  value: 0.3
learning_rate:
  desc: null
  value: 0.001
units_layer_1:
  desc: null
  value: 64
units_layer_2:
  desc: null
  value: 32
