wandb_version: 1

batch_size:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 600
learning_rate:
  value: 0.0001
num_layers:
  value: 1
units_layer_1:
  value: 128
units_layer_2:
  value: 64
