wandb_version: 1

batch_size:
  value: 128
dropout_rate:
  value: 0.2
epochs:
  value: 100
learning_rate:
  value: 0.0001
num_layers:
  value: 3
units_layer_1:
  value: 256
units_layer_2:
  value: 64
