wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.3
epochs:
  value: 300
learning_rate:
  value: 0.0001
num_layers:
  value: 2
units_layer_1:
  value: 256
units_layer_2:
  value: 256
